### PR TITLE
Align editor-popup-panel text

### PR DESCRIPTION
**Pull request by CharlRitterCompany**
Align editor-popup-panel text

### Description
Align editor-popup-panel text

### Issue
https://spandigital.atlassian.net/browse/PRSDM-2971

### Testing
Confirmed the text is now centred

### Screenshots
Screenshot 2022-11-30 at 11 25 51
Screenshot 2022-11-30 at 11 26 29

### Checklist before merging

* [x] Did you test your changes locally?
* [x] Did you update the CHANGELOG?
* [ ] Is the documentation updated for this change? (If Required)

### CODE REVIEW

**Review by effleurager — DISMISSED** [review]

**Comment by CharlRitterCompany** [comment]
updated screenshots

**Review by effleurager — CHANGES_REQUESTED** [review]
Change your base branch to `develop`, otherwise you'll merge straight into main.

**Comment by SamShiels** [comment]
The text still looks a bit off to me on the y-axis. Also, the OK button doesn't seem to be any different

**Review by mpilo-khathwane — APPROVED** [review]

**Comment by CharlRitterCompany** [comment]
New screencaps after more context.
Screenshot 2022-11-30 at 14 48 27
Screenshot 2022-11-30 at 14 49 01

**Comment by effleurager** [comment]
The error popup is centered according to the width of the entire popup, but the loading one excludes space for the spinner.

**Comment by CharlRitterCompany** [comment]
@effleurager I don't quite follow? I believe both would take the spinner/button into account.

**Comment by effleurager** [comment]
> @effleurager I don't quite follow? I believe both would take the spinner/button into account.

image

The problem is the alert popup reserves space on the left, whereas the loading one doesn't. None of the grid sizes are coordinated for symmetry, hence the _off_ look @SamShiels was mentioning

**Comment by CharlRitterCompany** [comment]
Screenshot 2022-11-30 at 15 53 09
Screenshot 2022-11-30 at 15 53 29

**Review by effleurager — APPROVED** [review]

**Comment by Zalaras** [comment]
Wont let me review but sent me an email... anyways Approved

**Review by SamShiels — CHANGES_REQUESTED** [review]
Screenshot 2022-12-01 at 10 14 27
The text is still misaligned unfortunately :( The spaces between the text and the top and bottom of the panel is not equal. Same goes for the text within the Ok button.

**Review by SamShiels — APPROVED** [review]

**Pull request merged**
