### PR TITLE
Removed unused styles

### PR DESCRIPTION
**Pull request by SamShiels**
Removed some unused styles for the article buttons.

### Issue
https://spandigital.atlassian.net/browse/PRSDM-3164

### Checklist before merging

* [x] Did you test your changes locally?
* [x] Did you update the CHANGELOG?
* [ ] Is the documentation updated for this change? (If Required)

### CODE REVIEW

**Review by christopherbrunsdon — APPROVED** [review]

**Comment by christopherbrunsdon** [comment]
Tested ... OK
* Chrome
* Safari

**Review by mpilo-khathwane — APPROVED** [review]

**Review by kmorake — APPROVED** [review]

**Comment by meyerhp** [comment]
@SamShiels please resolve conflicts

**Comment by SamShiels** [comment]
> @SamShiels please resolve conflicts

@meyerhp Done

**Comment by effleurager** [comment]
Empty PR?

**Pull request closed without merging**
